# egov-access \uc124\uc815
id = egovAccessConfig
globalAuthen = session
mappingPath = /**/*.do
dataSource = dataSource
loginUrl = /uat/uia/egovLoginUsr.do
accessDeniedUrl = /uat/uia/egovLoginUsr.do?auth_error=1
sqlAuthorityUser = select concat(b.user_se, b.user_id) userid, a.author_code authority from comtnemplyrscrtyestbs a, comvnusermaster b where a.scrty_dtrmn_trget_id = b.esntl_id
sqlRoleAndUrl = select a.role_pttrn url, b.author_code authority from comtnroleinfo a, comtnauthorrolerelate b where a.role_code = b.role_code and a.role_ty = 'url' order by a.role_sort
requestMatcherType = regex
excludeList = /css/**, /html/**, /images/**, /js/**, /resource/**, /index.do, /EgovLeft.do, /EgovContent.do, /EgovTop.do, /EgovBottom.do, /uat/uia/**, /validator.do, /uss/umt/**, /EgovModal.do
