# egov-crypto \uc124\uc815
id = egovCryptoConfig
initial = true
crypto = true
algorithm = SHA-256
algorithmKey = egovframe
algorithmKeyHash = gdyYs/IZqY86VcWhT8emCYfqY1ahw2vtLG+/FzNqtrQ=
cryptoBlockSize = 1024
cryptoPropertyLocation = classpath:/egovframework/egovProps/globals.properties
plainDigest = false
