# egov-security \uc124\uc815
id = egovSecurityConfig
loginUrl = /uat/uia/egovLoginUsr.do
loginProcessUrl = /uat/uia/actionSecurityProcess.do
logoutUrl = /uat/uia/actionSecurityLogout.do
logoutSuccessUrl = /uat/uia/egovLoginUsr.do
loginFailureUrl = /uat/uia/egovLoginUsr.do?login_error=1
accessDeniedUrl = /sec/ram/accessDenied.do
dataSource = egov.dataSource
jdbcUsersByUsernameQuery = SELECT USER_ID, ESNTL_ID AS PASSWORD, 1 ENABLED, USER_NM, USER_ZIP, USER_ADRES, USER_EMAIL, USER_SE, ORGNZT_ID, ESNTL_ID, (select a.ORGNZT_NM from COMTNORGNZTINFO a where a.ORGNZT_ID = m.ORGNZT_ID) ORGNZT_NM FROM COMVNUSERMASTER m WHERE CONCAT(USER_SE, USER_ID) = ?
jdbcAuthoritiesByUsernameQuery = SELECT A.SCRTY_DTRMN_TRGET_ID USER_ID, A.AUTHOR_CODE AUTHORITY FROM COMTNEMPLYRSCRTYESTBS A, COMVNUSERMASTER B WHERE A.SCRTY_DTRMN_TRGET_ID = B.ESNTL_ID AND B.USER_ID = ?
jdbcMapClass = egovframework.com.sec.security.common.EgovSessionMapping
requestMatcherType = regex
hash = plaintext
hashBase64 = false
concurrentMaxSessons = 1
concurrentExpiredUrl = /EgovContent.do
errorIfMaximumExceeded = false
defaultTargetUrl = /EgovContent.do
alwaysUseDefaultTargetUrl = true
sniff = true
xframeOptions = SAMEORIGIN
xssProtection = true
cacheControl = false
csrf = false
csrfAccessDeniedUrl = /egovCSRFAccessDenied.do
permitAllList = /css/**, /html/**, /images/**, /js/**, /resource/**, \\A/.*\\.jsp.*\\Z, \\A/WEB-INF/.*\\Z, \\A/uat/uia/.*\\.do.*\\Z, /, /index.do, /EgovTop.do, /EgovBottom.do, /EgovLeft.do, /EgovContent.do, /sec/ram/accessDenied.do, /egovCSRFAccessDenied.do, /cmm/fms/getImage.do, /uss/ion/bnr/getBannerImage.do, /twitter/login.do, /twitter/callback.do, /egovframe-template-common-components/twitter/login.do, /egovframe-template-common-components/twitter/callback.do, \\A/twitter/.*\\.do.*\\Z, \\A/.*/twitter/.*\\.do.*\\Z
sqlHierarchicalRoles = SELECT a.CHLDRN_ROLE as child, a.PARNTS_ROLE parent FROM COMTNROLES_HIERARCHY a LEFT JOIN COMTNROLES_HIERARCHY b on (a.CHLDRN_ROLE = b.PARNTS_ROLE)
sqlRolesAndUrl = SELECT a.ROLE_PTTRN as url, b.AUTHOR_CODE authority FROM COMTNROLEINFO a, COMTNAUTHORROLERELATE b WHERE a.ROLE_CODE = b.ROLE_CODE AND a.ROLE_TY = 'url'  ORDER BY a.ROLE_SORT
sqlRegexMatchedRequestMapping = SELECT a.ROLE_PTTRN as uri, b.AUTHOR_CODE authority FROM COMTNROLEINFO a, COMTNAUTHORROLERELATE b WHERE a.ROLE_CODE = b.ROLE_CODE AND a.ROLE_TY = 'regex' ORDER BY a.ROLE_SORT

